### PR TITLE
edit artist for pull request

### PR DESCRIPTION
**Pull request by hossambeh**
# Egypt
- Hossam Hassan 
+ Manar Hassan
    * Mr Hossam Hasasn
-----
[Markdown tutorial](https://www.youtube.com/watch?v=bTVIMt3XllM)
----
## **Table of contents** 
1. [Installation](#installation)
1. [why Python?](#why-python)
### - ~~NOPE~~ 
**AYHAGA *WALA* EHH**
1.  Shoof eh el donia w 2oli

```py
def parse_bytes(input):
    import re
    pattern = re.compile(r'\b[10]{8}\b')
    res = pattern.findall(input)
    return res

print(parse_bytes("11010101 101 323"))
print(parse_bytes("my data is: 10101010 11100010"))
print(parse_bytes("asdsa"))
``` 

### Please agree on this and make a pull request

### CODE REVIEW

**Comment by Hossamster** [comment]
please fix x,y,z w ta3ala tani

**Comment by hossambeh** [comment]
okay  i will do my best 7ader

**Comment by hossambeh** [comment]
tayb we delwaty ehh el nezam ?

**Comment by Hossamster** [comment]
sho8l 3ali walahi yabni 
merging is coming.

**Pull request merged**
